---
title: "lab1_2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(skimr)
library(maps)
library(sf)
library(usmap)
library(tigris)

```

Code and data available at: https://github.com/sal2222/env_chem


## Read-in data

Source: USGS Water Quality Portal: https://www.waterqualitydata.us/ 

Query: Montgomery County, stream, inorganic, 2000-2022



```{r}

montgomery <- read_csv("data/resultphyschem_clean2022.csv", guess_max = 3000, na = c("", "NA", "ND")) %>% 
  mutate(StartDate = as.Date(StartDate, "%m/%d/%Y")) %>% 
  rename(ResultName = 'Result Name') 
  
# Needed guess_max to assign numeric (double) lat/lon column types; add "ND" to NA list 
                       
montgomery


```


## Inspect Data

```{r}

montgomery %>% skimr::skim()

# Bar chart of # of parameters analyzed by date

montgomery %>% 
  ggplot(aes(x = StartDate)) +
    geom_bar(stat = "count") +
  theme_bw()


# Parameter values

montgomery %>% 
  group_by(ResultName) %>%
  count() %>% 
  View()


montgomery %>% 
  group_by(ResultName, ResultType, ResultUnit) %>%
  filter(n() > 5) %>% 
  summarise(mean = mean(ResultValue),
              sd = sd(ResultValue),
              n = n()) %>% 
  knitr::kable()



```

## Map Siter

```{r}
# All states
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))

# All counties
counties <- st_as_sf(map("county", plot = FALSE, fill = TRUE))

# Filter Montgomery County, MD shapefile
montgomery_shape <- counties %>% 
  filter(ID %in% "maryland,montgomery")

# Filter dataframe to include only observations with coordinates, group by location ID
montgomery_map <-
    montgomery %>% 
      filter(!lat %in% NA) %>% 
  group_by(LocationID, lat, lon) %>% 
  count()
  
# sample sites from lat/lon  
sites <- st_as_sf(montgomery_map, coords = c("lon", "lat"), 
    crs = 4326, agr = "constant")




# Plot map


ggplot(data = montgomery_shape) +
    geom_sf() +
    geom_sf(data = sites)


# Gradient scale by number of samples

ggplot(data = montgomery_shape) +
    geom_sf() +
    geom_sf(data = sites, aes(fill = n), size = 3, shape = 23)


```


## Fancier map

```{r}

# Add details


my_bbox <- c(xmin = min(montgomery_map$lon),
             xmax = max(montgomery_map$lon),
             ymin = min(montgomery_map$lat),
             ymax = max(montgomery_map$lat))



roads <- tigris::roads("MD", "montgomery")
linear_water <- tigris::linear_water("MD", "montgomery")


ggplot(data = montgomery_shape) +
    geom_sf() +
    geom_sf(data = roads,
                   color = "tan", fill = "white", size = 0.1, alpha = 0.5) +
    geom_sf(data = linear_water,
                   color = "blue", fill = "white", size = 0.1, alpha = 0.5) +
    geom_sf(data = sites, aes(fill = n), size = 3, shape = 23) +
    theme_bw()


```





## Carbonate and Bicarbonate

```{r}


# Boxplot
montgomery %>% 
  filter(ResultName %in% c("Bicarbonate", "Carbonate")) %>% 
  ggplot(aes(x = ResultName, y = ResultValue)) +
    geom_boxplot() +
    coord_flip() +
    ylab("mg/L") +
    ggtitle("Carbonate Species") +
    theme_bw()


# Summary Table

montgomery %>% 
  filter(ResultName %in% c("Bicarbonate", "Carbonate")) %>% 
  group_by(ResultName) %>% 
    summarise(mean = round(mean(ResultValue), digits = 2),
              sd = round(sd(ResultValue), digits = 2),
              upper95 = round(quantile(ResultValue, .95), digits = 2),
              n = n()) %>% 
  knitr::kable()

montgomery %>% 
  filter(ResultName %in% c("Bicarbonate", "Carbonate")) %>% 
    View()


# Remove Outlier sample (units in ueq/L)

montgomery %>% 
  filter(ResultName %in% c("Bicarbonate", "Carbonate"),
         !OrgID %in% "NARS_WQX") %>% 
  ggplot(aes(x = ResultName, y = ResultValue)) +
    geom_boxplot() +
    coord_flip() +
    ylab("mg/L") +
    ggtitle("Carbonate Species") +
    theme_bw()




```


## Select parameter
```{r}

montgomery %>% 
  filter(ResultName %in% "Chloride" & ResultType %in% "Dissolved") %>% 
  ggplot(aes(x = StartDate, y = ResultValue)) +
    geom_point() +
    ggtitle("Chloride, dissolved (mg/L)") +
    theme_bw()

montgomery %>% 
  filter(ResultName %in% "Chloride" & ResultType %in% "Dissolved") %>% 
  ggplot(aes(x = StartDate, y = ResultValue, col = OrgID)) +
    geom_point() +
    ggtitle("Chloride, dissolved (mg/L)") +
    theme_bw()

```




